server:
  port: 8082
db:
  username: root
  password: welcome1  
management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      probes:
        enabled: true            